"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import { Download, Loader2 } from "lucide-react";

interface Report {
  id: string;
  user_id: string;
  input: {
    product_name: string;
    category: string;
    region: string;
    unit_price: number;
    current_inventory: number;
    prediction_date: string;
    model_type?: string;
  };
  output: {
    forecast_sales: number;
    projected_revenue: number;
    potential_waste_inr: number;
    risk_flags: string[];
    policy_impact: {
      repo_rate_effect: string;
      inflation_effect: string;
    };
  };
  created_at: string;
  modified_at: string | null;
}

interface ExportButtonProps {
  data: Report;
  userName?: string;
}

export default function ExportButton({
  data,
  userName = "Aganya User",
}: ExportButtonProps) {
  const [exporting, setExporting] = useState(false);

  const formatCurrency = (amount: number) => {
    // jsPDF default fonts do not support Rupee symbol (₹). Using "Rs." instead.
    const formatted = new Intl.NumberFormat("en-IN", {
      maximumFractionDigits: 0,
    }).format(amount);
    return `Rs. ${formatted}`;
  };

  const handleExport = async () => {
    setExporting(true);
    try {
      // Load Logo
      const getLogoBase64 = (): Promise<string> => {
        return new Promise((resolve, reject) => {
          const img = new Image();
          // Use absolute path with origin to avoid issues
          img.src = `${window.location.origin}/logo.png`;
          img.crossOrigin = "Anonymous";
          img.onload = () => {
            const canvas = document.createElement("canvas");

            // Resize logic to optimize PDF size
            const MAX_WIDTH = 300; // 300px is plenty for a 15mm print
            let width = img.width;
            let height = img.height;

            if (width > MAX_WIDTH) {
              height = (height * MAX_WIDTH) / width;
              width = MAX_WIDTH;
            }

            canvas.width = width;
            canvas.height = height;

            const ctx = canvas.getContext("2d");
            ctx?.drawImage(img, 0, 0, width, height);
            resolve(canvas.toDataURL("image/png"));
          };
          img.onerror = () => {
            // Fallback or just resolve null to not break PDF
            console.warn("Logo failed to load");
            resolve("");
          };
        });
      };

      let logoData: string | null = null;
      try {
        logoData = await getLogoBase64();
      } catch (e) {
        console.warn("Could not load logo", e);
      }

      // 1. Initialize PDF (A4 Portrait)
      const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 15;
      let cursorY = 0;

      // 2. Header Section
      doc.setFillColor(20, 184, 166); // Teal-500
      doc.rect(0, 0, pageWidth, 25, "F");

      // Logo
      if (logoData) {
        doc.addImage(logoData, "PNG", margin, 5, 15, 15); // 15x15mm logo
      }

      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(20);
      // Shift text if logo exists
      doc.text("Aganya AI", margin + (logoData ? 18 : 0), 17);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text("Demand Intelligence Report", pageWidth - margin - 45, 17);

      cursorY = 40;

      // 3. Report Title & Info
      doc.setTextColor(30, 30, 30);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.text(data.input.product_name, margin, cursorY);

      cursorY += 8;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);

      const dateStr = new Date(data.input.prediction_date).toLocaleDateString(
        "en-IN",
        {
          day: "numeric",
          month: "long",
          year: "numeric",
        },
      );
      doc.text(`Forecast Date: ${dateStr}`, margin, cursorY);
      doc.text(
        `Region: ${data.input.region}  |  Category: ${data.input.category}`,
        margin,
        cursorY + 5,
      );

      // User Info (Right aligned)
      doc.text(`Generated by: ${userName}`, pageWidth - margin - 50, cursorY);
      doc.text(
        `Date: ${new Date().toLocaleDateString()}`,
        pageWidth - margin - 50,
        cursorY + 5,
      );

      cursorY += 15;

      // Forecast Period Disclaimer Box
      doc.setDrawColor(59, 130, 246); // Blue border
      doc.setFillColor(239, 246, 255); // Light blue background
      doc.rect(margin, cursorY, pageWidth - 2 * margin, 15, "FD");

      doc.setFontSize(8);
      doc.setTextColor(37, 99, 235); // Blue text
      doc.setFont("helvetica", "bold");
      doc.text("Forecast Period Notice:", margin + 3, cursorY + 5);

      doc.setFont("helvetica", "normal");
      const disclaimerText = `This prediction represents expected demand for approximately 30 days around ${dateStr}, using macro-economic conditions (Repo Rate, CPI, GDP) applicable to that period.`;
      const splitText = doc.splitTextToSize(
        disclaimerText,
        pageWidth - 2 * margin - 6,
      );
      doc.text(splitText, margin + 3, cursorY + 9);

      cursorY += 20;

      // 4. Metrics Grid (Row of 3 Boxes)
      const boxWidth = (pageWidth - 2 * margin - 10) / 3;
      const boxHeight = 25;

      // Box 1: Forecast Sales
      doc.setDrawColor(230, 230, 230);
      doc.setFillColor(245, 245, 245);
      doc.rect(margin, cursorY, boxWidth, boxHeight, "FD");

      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text("Forecast Sales", margin + 5, cursorY + 8);

      doc.setFontSize(14);
      doc.setTextColor(30, 30, 30);
      doc.setFont("helvetica", "bold");
      doc.text(`${data.output.forecast_sales} units`, margin + 5, cursorY + 18);

      // Box 2: Revenue
      doc.setFillColor(236, 253, 245); // Teal tint
      doc.setDrawColor(20, 184, 166); // Teal border
      doc.rect(margin + boxWidth + 5, cursorY, boxWidth, boxHeight, "FD");

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(20, 184, 166);
      doc.text("Projected Revenue", margin + boxWidth + 10, cursorY + 8);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text(
        formatCurrency(data.output.projected_revenue),
        margin + boxWidth + 10,
        cursorY + 18,
      );

      // Box 3: Waste
      doc.setDrawColor(239, 68, 68); // Red border
      doc.setFillColor(254, 242, 242); // Red tint
      doc.rect(margin + boxWidth * 2 + 10, cursorY, boxWidth, boxHeight, "FD");

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(239, 68, 68);
      doc.text("Potential Waste", margin + boxWidth * 2 + 15, cursorY + 8);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text(
        formatCurrency(data.output.potential_waste_inr),
        margin + boxWidth * 2 + 15,
        cursorY + 18,
      );

      cursorY += 40;

      // 5. Input Parameters Table
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(30, 30, 30);
      doc.text("Configuration Parameters", margin, cursorY);

      cursorY += 5;
      doc.line(margin, cursorY, pageWidth - margin, cursorY); // Divider
      cursorY += 10;

      const params = [
        ["Unit Price", formatCurrency(data.input.unit_price)],
        ["Current Inventory", `${data.input.current_inventory} units`],
        ["Region", data.input.region],
        ["Region", data.input.region],
        ["Category", data.input.category],
        ["Model Engine", (data.input.model_type || "Advanced").toUpperCase()],
      ];

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);

      params.forEach(([label, value], i) => {
        const xPos = margin + (i % 2) * (pageWidth / 2);
        const yPos = cursorY + Math.floor(i / 2) * 10;

        doc.setTextColor(100, 100, 100);
        doc.text(`${label}:`, xPos, yPos);

        doc.setTextColor(30, 30, 30);
        doc.text(value, xPos + 35, yPos);
      });

      cursorY += 30;

      // 6. Analysis Sections (Risks & Policy)
      // Left Column: Risk Flags
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text("Risk Analysis", margin, cursorY);

      let riskCursorY = cursorY + 10;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(220, 38, 38); // Red

      if (data.output.risk_flags.length > 0) {
        data.output.risk_flags.forEach((flag) => {
          doc.text(`• ${flag}`, margin, riskCursorY);
          riskCursorY += 7;
        });
      } else {
        doc.setTextColor(20, 184, 166);
        doc.text("• Low Risk Detected", margin, riskCursorY);
      }

      // Right Column: Policy Impact
      const col2X = pageWidth / 2 + 10;
      doc.setTextColor(30, 30, 30);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text("Policy Impact", col2X, cursorY);

      let policyCursorY = cursorY + 10;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(80, 80, 80);

      doc.text(`Repo Rate:`, col2X, policyCursorY);
      doc.text(
        data.output.policy_impact.repo_rate_effect,
        col2X,
        policyCursorY + 5,
      );

      policyCursorY += 15;
      doc.text(`Inflation:`, col2X, policyCursorY);
      doc.text(
        data.output.policy_impact.inflation_effect,
        col2X,
        policyCursorY + 5,
      );

      // 7. Footer
      const footerY = pageHeight - 20;
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);

      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);

      // Potential Waste Explanation
      doc.setFont("helvetica", "bold");
      doc.text("Potential Waste (Holding Cost):", margin, footerY);
      doc.setFont("helvetica", "normal");
      const wasteExplanation =
        "Estimated holding cost for excess inventory (20% of unsold units value, accounting for storage, insurance, depreciation).";
      const wasteText = doc.splitTextToSize(
        wasteExplanation,
        pageWidth - 2 * margin,
      );
      doc.text(wasteText, margin, footerY + 3);

      // AI Disclaimer
      doc.text(
        "Disclaimer: This report is generated by an AI model for informational purposes only. Aganya AI does not guarantee 100% accuracy.",
        margin,
        footerY + 10,
      );

      // 8. Save
      doc.save(
        `Aganya_Report_${data.input.product_name.replace(/\s+/g, "_")}.pdf`,
      );
    } catch (err) {
      console.error("Export failed", err);
      alert("Failed to create PDF");
    } finally {
      setExporting(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={exporting}
      className="flex items-center gap-2 px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-white rounded-xl transition-all border border-zinc-700 disabled:opacity-50"
    >
      {exporting ? (
        <Loader2 className="w-4 h-4 animate-spin" />
      ) : (
        <Download className="w-4 h-4" />
      )}
      <span>{exporting ? "Generating..." : "Export PDF"}</span>
    </button>
  );
}
